#!/bin/sh
echo --------------------------------------------
echo Starting docs generation

npm run generate-all-docs;

git add docs

echo Finished docs generation
echo --------------------------------------------
